BN:
  NUM_SAMPLES_PRECISE: 1024
  ZERO_INIT_FINAL_GAMMA: true
CHECKPT_DIR: ..
CUDNN:
  BENCHMARK: true
DATA_LOADER:
  NUM_WORKERS: 4
MODEL:
  LAYERS: 6
  NUM_CLASSES: 100
  TYPE: cnn
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: true
  WEIGHT_DECAY: 0.009
OUT_DIR: .
RESNET:
  TRANS_FUN: convtalk_transform
RGRAPH:
  ADD_1x1: 0
  AGG_FUNC: sum
  DIM_FIRST: 64
  DIM_LIST:
  - 64
  - 128
  - 256
  GROUP_NUM: 64
  KEEP_GRAPH: true
  MESSAGE_TYPE: ws
  P: 0.066319
  SEED_GRAPH: 13
  SEED_TRAIN_END: 31
#   SEED_TRAIN_END: 2
  SEED_TRAIN_START: 1
  SPARSITY: 0.23357
  STEM_MODE: default
  TALK_MODE: dense
  UPPER: true
TEST:
  BATCH_SIZE: 600
  DATASET: cifar100
  SPLIT: test
TRAIN:
  AUTO_MATCH: true
  BATCH_SIZE: 640
  CHECKPOINT_PERIOD: 100
  DATASET: cifar100
  EVAL_PERIOD: 1
  SPLIT: train
