MODEL:
  TYPE: resnet
  DEPTH: 18
  NUM_CLASSES: 1000
RESNET:
  TRANS_FUN: channelbasic_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
RGRAPH:
  DIM_LIST: [64,128,256,512]
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: steps
  STEPS: [0, 25, 50, 70]
  LR_MULT: 0.1
  MAX_EPOCH: 75
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 450
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 25
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 400
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
