MODEL:
  TYPE: cnn
  NUM_CLASSES: 10
  LAYERS: 6
RESNET:
  TRANS_FUN: convbasic_transform
RGRAPH:
  GROUP_NUM: 64
  DIM_FIRST: 64
  DIM_LIST: [64,128,256]
  STEM_MODE: default
BN:
  ZERO_INIT_FINAL_GAMMA: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
#   WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY: 0.01
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 1024
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 50
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 512
  INFERENCE: true
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 12
CUDNN:
  BENCHMARK: True
OUT_DIR: .
