MODEL:
  TYPE: resnet
  DEPTH: 18
  NUM_CLASSES: 200
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
RGRAPH:
  DIM_LIST: [64,128,256,512]
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 75
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.006
TRAIN:
  DATASET: tinyimagenet200
  SPLIT: train
  BATCH_SIZE: 256
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 25
TEST:
  DATASET: tinyimagenet200
  SPLIT: val
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 12
CUDNN:
  BENCHMARK: True
OUT_DIR: .
